import notionPost0 from '../notion-data/3b8f909c-3e9d-8004-865b-e5cee7703f08.json'
import type { Post } from './post'

// This file is generated by `npm run sync:notion`. Do not edit it manually.
const notionPosts: Post[] = [
  {
    "notionPageId": "3b8f909c-3e9d-8004-865b-e5cee7703f08",
    "title": "C# 코드는 어떻게 실행되는가 - 1편, .NET과 C#",
    "slug": "csharp01-post",
    "date": "2026-08-10",
    "description": ".NET과 C#에 대한 기초",
    "image": "/notion-data/3b8f909c-3e9d-8004-865b-e5cee7703f08/thumbnail.png",
    "tags": [
      "C#"
    ],
    "content": notionPost0
  }
]

export default notionPosts
