import notionPost0 from '../notion-data/3b8f909c-3e9d-8004-865b-e5cee7703f08.json'
import type { Post } from './post'

// This file is generated by `npm run sync:notion`. Do not edit it manually.
const notionPosts: Post[] = [
  {
    "notionPageId": "3b8f909c-3e9d-8004-865b-e5cee7703f08",
    "title": "C#의 전략과 실행 구조",
    "slug": "test-post",
    "date": "2026-08-10",
    "description": "자동화를 확인하기 위한 글입니다.",
    "image": "/notion-data/3b8f909c-3e9d-8004-865b-e5cee7703f08/thumbnail.png",
    "tags": [
      "Test"
    ],
    "content": notionPost0
  }
]

export default notionPosts
